#include "data.h"

const Entry EMBEDDED_ENTRIES[] = {
    {1, 1, "Laimnesis, Solvita, Solvija"},
    {1, 2, "Indulis, Ivo, Iva, Ivis"},
    {1, 3, "Miervaldis, Miervalda, Ringolds"},
    {1, 4, "Spodra, Ilva, Ilvita"},
    {1, 5, "Sīmanis, Zintis"},
    {1, 6, "Spulga, Arnita"},
    {1, 7, "Rota, Zigmārs, Juliāns, Digmārs"},
    {1, 8, "Gatis, Ivanda"},
    {1, 9, "Kaspars, Aksels, Alta"},
    {1, 10, "Tatjana, Dorisa"},
    {1, 11, "Smaida, Franciska"},
    {1, 12, "Reinis, Reina, Reinholds, Renāts"},
    {1, 13, "Harijs, Ārijs, Āris, Aira"},
    {1, 14, "Roberts, Roberta, Raitis, Raits"},
    {1, 15, "Fēlikss, Felicita"},
    {1, 16, "Lidija, Lida"},
    {1, 17, "Tenis, Dravis"},
    {1, 18, "Antons, Antis, Antonijs"},
    {1, 19, "Andulis, Alnis"},
    {1, 20, "Oļģerts, Orests, Aļģirds, Aļģis"},
    {1, 21, "Agnese, Agnija, Agne"},
    {1, 22, "Austris"},
    {1, 23, "Grieta, Strauta, Rebeka"},
    {1, 24, "Krišs, Ksenija, Eglons, Egle"},
    {1, 25, "Zigurds, Sigurds, Sigvards"},
    {1, 26, "Ansis, Agnis, Agneta"},
    {1, 27, "Ilze, Ildze, Izolde"},
    {1, 28, "Kārlis, Spodris"},
    {1, 29, "Aivars, Valērijs, Bille"},
    {1, 30, "Tīna, Valentīna, Pārsla"},
    {1, 31, "Tekla, Violeta"},
    {2, 1, "Brigita, Indra, Indars, Indris"},
    {2, 2, "Spīdola, Sonora"},
    {2, 3, "Aīda, Ida, Vida"},
    {2, 4, "Daila, Veronika, Dominiks"},
    {2, 5, "Agate, Selga, Silga, Sinilga"},
    {2, 6, "Dace, Dārta, Dora, Daris"},
    {2, 7, "Nelda, Rihards, Ričards, Rišards"},
    {2, 8, "Aldona, Česlavs"},
    {2, 9, "Simona, Apolonija"},
    {2, 10, "Paulīne, Paula, Jasmīna"},
    {2, 11, "Laima, Laimdota"},
    {2, 12, "Karlīna, Līna"},
    {2, 13, "Malda, Melita"},
    {2, 14, "Valentīns"},
    {2, 15, "Alvils, Olafs, Aloizs, Olavs"},
    {2, 16, "Jūlija, Džuljeta"},
    {2, 17, "Donats, Konstance"},
    {2, 18, "Kora, Kintija"},
    {2, 19, "Zane, Zuzanna"},
    {2, 20, "Vitauts, Smuidra, Smuidris"},
    {2, 21, "Eleonora, Ariadne"},
    {2, 22, "Ārija, Rigonda, Adrians, Adriāna, Adrija"},
    {2, 23, "Haralds, Almants"},
    {2, 24, "Diāna, Dina, Dins"},
    {2, 25, "Alma, Annemarija"},
    {2, 26, "Evelīna, Aurēlija, Mētra"},
    {2, 27, "Līvija, Līva, Andra"},
    {2, 28, "Skaidrīte, Justs, Skaidra"},
    {3, 1, "Ivars, Ilgvars"},
    {3, 2, "Lavīze, Luīze, Laila"},
    {3, 3, "Tālis, Tālavs, Marts"},
    {3, 4, "Alise, Auce, Enija"},
    {3, 5, "Austra, Aurora, Aurika"},
    {3, 6, "Vents, Centis, Gotfrīds"},
    {3, 7, "Ella, Elmīra"},
    {3, 8, "Dagmāra, Marga, Margita"},
    {3, 9, "Ēvalds"},
    {3, 10, "Silvija, Laimrota, Liliāna"},
    {3, 11, "Konstantīns, Agita"},
    {3, 12, "Aija, Aiva, Aivis"},
    {3, 13, "Ernests, Balvis"},
    {3, 14, "Matilde, Ulrika"},
    {3, 15, "Amilda, Amalda, Imalda"},
    {3, 16, "Guntis, Guntars, Guntris"},
    {3, 17, "Ģertrūde, Gerda, Gerhards"},
    {3, 18, "Ilona, Adelīna"},
    {3, 19, "Jāzeps, Juzefa"},
    {3, 20, "Made, Irbe"},
    {3, 21, "Una, Unigunde, Dzelme, Benedikts, Benedikta"},
    {3, 22, "Tamāra, Dziedra, Gabriels, Gabriela"},
    {3, 23, "Mirdza, Žanete, Žanna"},
    {3, 24, "Kazimirs, Izidors"},
    {3, 25, "Māra, Mārīte, Marita, Mare, Ģedimins"},
    {3, 26, "Eiženija, Ženija"},
    {3, 27, "Gustavs, Gusts, Tālrīts, Saulis"},
    {3, 28, "Gunta, Ginta, Gunda"},
    {3, 29, "Aldonis, Agija"},
    {3, 30, "Nanija, Ilgmārs"},
    {3, 31, "Gvido, Atvars"},
    {4, 1, "Dagnis, Dagne"},
    {4, 2, "Irmgarde"},
    {4, 3, "Daira, Dairis, Daiva, Daivis"},
    {4, 4, "Valda, Herta, Ārvalda, Ārvalds, Ārvaldis"},
    {4, 5, "Vija, Vidaga, Aivija"},
    {4, 6, "Zinta, Vīlips, Filips, Dzinta, Dzintis"},
    {4, 7, "Zina, Zinaīda, Helmuts"},
    {4, 8, "Edgars, Danute, Dana, Dans"},
    {4, 9, "Valērija, Žubīte, Alla"},
    {4, 10, "Anita, Anitra, Zīle, Annika"},
    {4, 11, "Hermanis, Vilmārs"},
    {4, 12, "Jūlijs, Ainis"},
    {4, 13, "Egils, Egīls, Nauris"},
    {4, 14, "Strauja, Gudrīte"},
    {4, 15, "Aelita, Gastons"},
    {4, 16, "Mintauts, Alfs, Bernadeta"},
    {4, 17, "Rūdolfs, Viviāna, Rūdis"},
    {4, 18, "Laura, Jadviga"},
    {4, 19, "Vēsma, Fanija"},
    {4, 20, "Mirta, Ziedīte, Meija"},
    {4, 21, "Marģers, Anastasija"},
    {4, 22, "Armands, Armanda"},
    {4, 23, "Jurģis, Juris, Georgs, Jurgita"},
    {4, 24, "Visvaldis, Nameda, Ritvaldis, Ritums"},
    {4, 25, "Līksma, Bārbala"},
    {4, 26, "Alīna, Sandris, Rūsiņš"},
    {4, 27, "Tāle, Raimonda, Raina, Klementīne"},
    {4, 28, "Gundega, Terēze"},
    {4, 29, "Vilnis, Raimonds, Laine"},
    {4, 30, "Lilija, Liāna"},
    {5, 1, "Ziedonis"},
    {5, 2, "Zigmunds, Sigmunds, Zigismunds"},
    {5, 3, "Gints, Uvis"},
    {5, 4, "Vizbulīte, Viola, Vijolīte"},
    {5, 5, "Ģirts, Ģederts"},
    {5, 6, "Gaidis, Didzis"},
    {5, 7, "Henriete, Henrijs, Jete, Enriko"},
    {5, 8, "Staņislavs, Staņislava, Stefānija"},
    {5, 9, "Klāvs, Einārs, Ervīns"},
    {5, 10, "Maija, Paija"},
    {5, 11, "Milda, Karmena, Manfreds"},
    {5, 12, "Valija, Ināra, Ina, Inārs"},
    {5, 13, "Irēna, Irīna, Ira, Iraīda"},
    {5, 14, "Krišjānis, Elfa, Aivita, Elvita"},
    {5, 15, "Sofija, Taiga, Airita, Arita"},
    {5, 16, "Edvīns, Edijs"},
    {5, 17, "Herberts, Dailis, Umberts"},
    {5, 18, "Inese, Inesis, Ēriks"},
    {5, 19, "Lita, Sibilla, Teika"},
    {5, 20, "Venta, Salvis, Selva"},
    {5, 21, "Ernestīne, Ingmārs, Akvelīna"},
    {5, 22, "Emīlija. Visu neparasto un kalendāros neierakstīto vārdu diena"},
    {5, 23, "Leontīne, Leokādija, Lonija, Ligija"},
    {5, 24, "Ilvija, Marlēna, Ziedone"},
    {5, 25, "Anšlavs, Junora"},
    {5, 26, "Edvards, Edvarts, Eduards, Varis"},
    {5, 27, "Dzidra, Gunita, Loreta, Dzidris"},
    {5, 28, "Vilis, Vilhelms"},
    {5, 29, "Maksis, Maksims, Raivis, Raivo"},
    {5, 30, "Vitolds, Lolita, Letīcija"},
    {5, 31, "Alīda, Jūsma"},
    {6, 1, "Biruta, Mairita, Bernedīne"},
    {6, 2, "Lība, Emma"},
    {6, 3, "Inta, Ineta, Intra"},
    {6, 4, "Elfrīda, Sintija, Sindija"},
    {6, 5, "Igors, Margots, Ingvars"},
    {6, 6, "Ingrīda, Ardis"},
    {6, 7, "Gaida, Arnis, Arno"},
    {6, 8, "Frīdis, Frīda, Mundra"},
    {6, 9, "Ligita, Gita"},
    {6, 10, "Malva, Anatols, Anatolijs"},
    {6, 11, "Ingus, Mairis, Vidvuds"},
    {6, 12, "Nora, Lenora, Ija"},
    {6, 13, "Zigfrīds, Ainārs, Uva"},
    {6, 14, "Tija, Saiva, Sentis, Santis, Saivis"},
    {6, 15, "Baņuta, Žermēna, Vilija, Vits"},
    {6, 16, "Justīne, Juta"},
    {6, 17, "Artūrs, Artis"},
    {6, 18, "Alberts, Madis"},
    {6, 19, "Viktors, Nils"},
    {6, 20, "Rasma, Rasa, Maira"},
    {6, 21, "Emīls, Egita, Monvīds"},
    {6, 22, "Ludmila, Laimdots, Laimiņš"},
    {6, 23, "Līga"},
    {6, 24, "Jānis"},
    {6, 25, "Milija, Maiga"},
    {6, 26, "Ausma, Inguna, Ingūna, Inguns, Ausmis"},
    {6, 27, "Malvīne, Malvis"},
    {6, 28, "Viesturs, Kitija, Viestards"},
    {6, 29, "Pēteris, Pāvils, Pauls, Paulis"},
    {6, 30, "Tālivaldis, Mareks"},
    {7, 1, "Imants, Rimants, Ingars, Intars"},
    {7, 2, "Lauma, Ilvars, Halina"},
    {7, 3, "Benita, Everita, Verita, Emerita"},
    {7, 4, "Ulvis, Uldis, Sandis, Sandijs"},
    {7, 5, "Andžs, Andžejs, Edīte, Esmeralda"},
    {7, 6, "Anrijs, Arkādijs"},
    {7, 7, "Alda, Maruta"},
    {7, 8, "Antra, Adele, Ada"},
    {7, 9, "Zaiga, Asne, Asna"},
    {7, 10, "Lija, Olīvija, Olivers, Odrija"},
    {7, 11, "Leonora, Svens"},
    {7, 12, "Indriķis, Ints, Namejs"},
    {7, 13, "Margrieta, Margarita"},
    {7, 14, "Oskars, Ritvars, Anvars"},
    {7, 15, "Egons, Egmonts, Egija, Henriks, Heinrihs"},
    {7, 16, "Hermīne, Estere, Liepa"},
    {7, 17, "Aleksis, Aleksejs, Alekss"},
    {7, 18, "Rozālija, Roze"},
    {7, 19, "Jautrīte, Kamila, Digna, Sāra"},
    {7, 20, "Ritma, Ramona"},
    {7, 21, "Meldra, Meldris, Melisa"},
    {7, 22, "Marija, Marika, Marina"},
    {7, 23, "Magda, Magone, Mērija, Magdalēna"},
    {7, 24, "Kristīne, Kristīna, Krista, Kristiāna, Kristiāns"},
    {7, 25, "Jēkabs, Žaklīna"},
    {7, 26, "Anna, Ance, Annija"},
    {7, 27, "Marta, Dita, Dite"},
    {7, 28, "Cecīlija, Cilda"},
    {7, 29, "Edmunds, Edžus, Vidmants"},
    {7, 30, "Valters, Renārs, Regnārs"},
    {7, 31, "Rūta, Ruta, Angelika, Sigita"},
    {8, 1, "Albīns, Albīna"},
    {8, 2, "Normunds, Stefans"},
    {8, 3, "Augusts"},
    {8, 4, "Romāns, Romualds, Romualda"},
    {8, 5, "Osvalds, Arvils"},
    {8, 6, "Askolds, Aisma"},
    {8, 7, "Alfrēds, Madars, Fredis"},
    {8, 8, "Mudīte, Vladislavs, Vladislava"},
    {8, 9, "Madara, Genoveva, Genovefa"},
    {8, 10, "Brencis, Audris, Inuta, Audra"},
    {8, 11, "Olga, Zita, Liega, Zigita"},
    {8, 12, "Vizma, Klāra"},
    {8, 13, "Elvīra, Velga, Rēzija"},
    {8, 14, "Zelma, Zemgus, Virma"},
    {8, 15, "Zenta, Dzelde, Zelda"},
    {8, 16, "Astra, Astrīda"},
    {8, 17, "Vineta, Oļegs"},
    {8, 18, "Liene, Helēna, Elena, Ellena, Liena"},
    {8, 19, "Melānija, Imanta"},
    {8, 20, "Bernhards, Boriss, Rojs"},
    {8, 21, "Janīna, Linda"},
    {8, 22, "Rudīte, Everts"},
    {8, 23, "Vitālijs, Ralfs, Valgudis"},
    {8, 24, "Bērtulis, Boļeslavs"},
    {8, 25, "Ludvigs, Ludis, Ivonna, Patrīcija, Patriks"},
    {8, 26, "Natālija, Tālija, Broņislavs, Broņislava"},
    {8, 27, "Žanis, Jorens, Alens"},
    {8, 28, "Auguste, Guste"},
    {8, 29, "Armīns, Vismants, Aiga"},
    {8, 30, "Alvis, Jolanta, Samanta"},
    {8, 31, "Vilma, Aigars"},
    {9, 1, "Ilmārs, Iluta, Austrums"},
    {9, 2, "Elīza, Lizete, Zete"},
    {9, 3, "Berta, Bella"},
    {9, 4, "Dzintra, Dzintara, Dzintars"},
    {9, 5, "Klaudija, Persijs, Vaida"},
    {9, 6, "Maigonis, Magnuss, Mariuss"},
    {9, 7, "Regīna, Ermīns"},
    {9, 8, "Ilga"},
    {9, 9, "Bruno, Telma"},
    {9, 10, "Jausma, Albertīne"},
    {9, 11, "Signe, Signija"},
    {9, 12, "Erna, Evita, Eva"},
    {9, 13, "Iza, Izabella"},
    {9, 14, "Sanita, Santa, Sanda, Sanija, Sandija"},
    {9, 15, "Sandra, Gunvaldis, Gunvaris, Sondra"},
    {9, 16, "Asja, Asnate, Dāgs"},
    {9, 17, "Vera, Vaira, Vairis, Vaiva"},
    {9, 18, "Liesma, Elita, Alita"},
    {9, 19, "Verners, Muntis"},
    {9, 20, "Guntra, Ginters, Marianna"},
    {9, 21, "Modris, Matīss, Mariss"},
    {9, 22, "Māris, Mārica, Maigurs"},
    {9, 23, "Vanda, Veneranda, Venija"},
    {9, 24, "Agris, Agrita"},
    {9, 25, "Rodrigo, Rauls"},
    {9, 26, "Gundars, Kurts, Knuts"},
    {9, 27, "Ādolfs, Ilgonis"},
    {9, 28, "Sergejs, Svetlana, Lana"},
    {9, 29, "Miķelis, Mikus, Miks, Mihails, Jumis"},
    {9, 30, "Elma, Menarda, Elna"},
    {10, 1, "Zanda, Lāsma, Zandis"},
    {10, 2, "Ilma, Skaidris"},
    {10, 3, "Elza, Ilizana"},
    {10, 4, "Modra, Francis, Dmitrijs"},
    {10, 5, "Amālija, Amēlija"},
    {10, 6, "Monika, Zilgma, Zilga"},
    {10, 7, "Daumants, Druvvaldis"},
    {10, 8, "Aina, Anete"},
    {10, 9, "Elga, Helga, Elgars"},
    {10, 10, "Arvīds, Arvis, Druvis"},
    {10, 11, "Monta, Tince, Silva"},
    {10, 12, "Valfrīds, Kira"},
    {10, 13, "Irma, Mirga"},
    {10, 14, "Vilhelmīne, Minna"},
    {10, 15, "Eda, Hedviga, Helvijs"},
    {10, 16, "Daiga, Dinija, Dinārs"},
    {10, 17, "Gaits, Karīna, Gaitis"},
    {10, 18, "Rolands, Rolanda, Ronalds, Erlends, Lūkass"},
    {10, 19, "Elīna, Drosma, Drosmis"},
    {10, 20, "Leonīds, Leonīda"},
    {10, 21, "Urzula, Severīns"},
    {10, 22, "Īrisa, Irīda, Airisa"},
    {10, 23, "Daina, Dainis, Dainida"},
    {10, 24, "Renāte, Modrīte, Mudrīte"},
    {10, 25, "Beāte, Beatrise"},
    {10, 26, "Amanda, Kaiva, Amanta"},
    {10, 27, "Lilita, Irita, Ita"},
    {10, 28, "Ņina, Ninona, Antoņina, Oksana"},
    {10, 29, "Laimonis, Elvijs, Elva, Elvis, Laimis"},
    {10, 30, "Nadīna, Ulla, Adīna"},
    {10, 31, "Valts, Rinalds, Rinalda"},
    {11, 1, "Ikars"},
    {11, 2, "Vivita, Dzīle, Viva"},
    {11, 3, "Ērika, Dagnija"},
    {11, 4, "Atis, Otomārs, Oto"},
    {11, 5, "Šarlote, Lote"},
    {11, 6, "Linards, Leons, Leo, Leonards, Leonarda"},
    {11, 7, "Helma, Lotārs, Pērle"},
    {11, 8, "Aleksandra, Agra"},
    {11, 9, "Teodors"},
    {11, 10, "Mārtiņš, Mārcis, Markuss, Marks"},
    {11, 11, "Ojārs, Rainers, Nellija"},
    {11, 12, "Kaija, Kornēlija"},
    {11, 13, "Eižens, Jevgeņijs, Jevgeņija"},
    {11, 14, "Fricis, Vikentijs, Vincents"},
    {11, 15, "Leopolds, Undīne, Unda"},
    {11, 16, "Banga, Glorija"},
    {11, 17, "Hugo, Uga, Uģis"},
    {11, 18, "Aleksandrs, Doloresa, Brīve"},
    {11, 19, "Elizabete, Liza, Līze, Betija"},
    {11, 20, "Anda, Andīna, Vigo"},
    {11, 21, "Zeltīte, Andis"},
    {11, 22, "Aldis, Alfons, Aldris"},
    {11, 23, "Zigrīda, Zigfrīda, Zigrīds"},
    {11, 24, "Velta, Velda"},
    {11, 25, "Katrīna, Kate, Kadrija, Trīne, Katrīne"},
    {11, 26, "Konrāds, Sebastians"},
    {11, 27, "Lauris, Norberts"},
    {11, 28, "Rita, Vita, Olita"},
    {11, 29, "Ignats, Virgīnija"},
    {11, 30, "Andrievs, Andrejs, Andris"},
    {12, 1, "Arnolds, Emanuels"},
    {12, 2, "Meta, Sniedze"},
    {12, 3, "Evija, Raita, Jogita, Ako"},
    {12, 4, "Baiba, Barbara, Barba"},
    {12, 5, "Sabīne, Sarma, Klaudijs"},
    {12, 6, "Nikolajs, Niklāvs, Niks, Nikola"},
    {12, 7, "Antonija, Anta, Dzirkstīte"},
    {12, 8, "Gunārs, Vladimirs, Gunis"},
    {12, 9, "Tabita, Sarmīte"},
    {12, 10, "Guna, Judīte"},
    {12, 11, "Voldemārs, Valdemārs, Valdis"},
    {12, 12, "Otīlija, Iveta"},
    {12, 13, "Lūcija, Veldze"},
    {12, 14, "Auseklis, Gaisma"},
    {12, 15, "Johanna, Hanna, Jana"},
    {12, 16, "Alvīne"},
    {12, 17, "Hilda, Teiksma"},
    {12, 18, "Kristaps, Kristofers, Krists, Klinta, Kristers"},
    {12, 19, "Lelde, Sarmis"},
    {12, 20, "Arta, Minjona"},
    {12, 21, "Toms, Tomass, Saulcerīte"},
    {12, 22, "Saulvedis, Saule"},
    {12, 23, "Viktorija, Balva"},
    {12, 24, "Ādams, Ieva"},
    {12, 25, "Stella, Larisa"},
    {12, 26, "Dainuvīte, Gija, Megija"},
    {12, 27, "Elmārs, Inita, Helmārs"},
    {12, 28, "Inga, Ivita, Irvita, Ingeborga"},
    {12, 29, "Solveiga, Ilgona"},
    {12, 30, "Dāvids, Dāvis, Dāniels, Daniela, Daniels"},
    {12, 31, "Silvestrs, Silvis, Kalvis"},
};

const size_t EMBEDDED_ENTRIES_COUNT = 365;

