package main

Entry :: struct {
    month: u8,
    day:   u8,
    names: string,
}

EMBEDDED_ENTRIES := [?]Entry{
    {month = 1, day = 1, names = "Laimnesis, Solvita, Solvija"},
    {month = 1, day = 2, names = "Indulis, Ivo, Iva, Ivis"},
    {month = 1, day = 3, names = "Miervaldis, Miervalda, Ringolds"},
    {month = 1, day = 4, names = "Spodra, Ilva, Ilvita"},
    {month = 1, day = 5, names = "Sīmanis, Zintis"},
    {month = 1, day = 6, names = "Spulga, Arnita"},
    {month = 1, day = 7, names = "Rota, Zigmārs, Juliāns, Digmārs"},
    {month = 1, day = 8, names = "Gatis, Ivanda"},
    {month = 1, day = 9, names = "Kaspars, Aksels, Alta"},
    {month = 1, day = 10, names = "Tatjana, Dorisa"},
    {month = 1, day = 11, names = "Smaida, Franciska"},
    {month = 1, day = 12, names = "Reinis, Reina, Reinholds, Renāts"},
    {month = 1, day = 13, names = "Harijs, Ārijs, Āris, Aira"},
    {month = 1, day = 14, names = "Roberts, Roberta, Raitis, Raits"},
    {month = 1, day = 15, names = "Fēlikss, Felicita"},
    {month = 1, day = 16, names = "Lidija, Lida"},
    {month = 1, day = 17, names = "Tenis, Dravis"},
    {month = 1, day = 18, names = "Antons, Antis, Antonijs"},
    {month = 1, day = 19, names = "Andulis, Alnis"},
    {month = 1, day = 20, names = "Oļģerts, Orests, Aļģirds, Aļģis"},
    {month = 1, day = 21, names = "Agnese, Agnija, Agne"},
    {month = 1, day = 22, names = "Austris"},
    {month = 1, day = 23, names = "Grieta, Strauta, Rebeka"},
    {month = 1, day = 24, names = "Krišs, Ksenija, Eglons, Egle"},
    {month = 1, day = 25, names = "Zigurds, Sigurds, Sigvards"},
    {month = 1, day = 26, names = "Ansis, Agnis, Agneta"},
    {month = 1, day = 27, names = "Ilze, Ildze, Izolde"},
    {month = 1, day = 28, names = "Kārlis, Spodris"},
    {month = 1, day = 29, names = "Aivars, Valērijs, Bille"},
    {month = 1, day = 30, names = "Tīna, Valentīna, Pārsla"},
    {month = 1, day = 31, names = "Tekla, Violeta"},
    {month = 2, day = 1, names = "Brigita, Indra, Indars, Indris"},
    {month = 2, day = 2, names = "Spīdola, Sonora"},
    {month = 2, day = 3, names = "Aīda, Ida, Vida"},
    {month = 2, day = 4, names = "Daila, Veronika, Dominiks"},
    {month = 2, day = 5, names = "Agate, Selga, Silga, Sinilga"},
    {month = 2, day = 6, names = "Dace, Dārta, Dora, Daris"},
    {month = 2, day = 7, names = "Nelda, Rihards, Ričards, Rišards"},
    {month = 2, day = 8, names = "Aldona, Česlavs"},
    {month = 2, day = 9, names = "Simona, Apolonija"},
    {month = 2, day = 10, names = "Paulīne, Paula, Jasmīna"},
    {month = 2, day = 11, names = "Laima, Laimdota"},
    {month = 2, day = 12, names = "Karlīna, Līna"},
    {month = 2, day = 13, names = "Malda, Melita"},
    {month = 2, day = 14, names = "Valentīns"},
    {month = 2, day = 15, names = "Alvils, Olafs, Aloizs, Olavs"},
    {month = 2, day = 16, names = "Jūlija, Džuljeta"},
    {month = 2, day = 17, names = "Donats, Konstance"},
    {month = 2, day = 18, names = "Kora, Kintija"},
    {month = 2, day = 19, names = "Zane, Zuzanna"},
    {month = 2, day = 20, names = "Vitauts, Smuidra, Smuidris"},
    {month = 2, day = 21, names = "Eleonora, Ariadne"},
    {month = 2, day = 22, names = "Ārija, Rigonda, Adrians, Adriāna, Adrija"},
    {month = 2, day = 23, names = "Haralds, Almants"},
    {month = 2, day = 24, names = "Diāna, Dina, Dins"},
    {month = 2, day = 25, names = "Alma, Annemarija"},
    {month = 2, day = 26, names = "Evelīna, Aurēlija, Mētra"},
    {month = 2, day = 27, names = "Līvija, Līva, Andra"},
    {month = 2, day = 28, names = "Skaidrīte, Justs, Skaidra"},
    {month = 3, day = 1, names = "Ivars, Ilgvars"},
    {month = 3, day = 2, names = "Lavīze, Luīze, Laila"},
    {month = 3, day = 3, names = "Tālis, Tālavs, Marts"},
    {month = 3, day = 4, names = "Alise, Auce, Enija"},
    {month = 3, day = 5, names = "Austra, Aurora, Aurika"},
    {month = 3, day = 6, names = "Vents, Centis, Gotfrīds"},
    {month = 3, day = 7, names = "Ella, Elmīra"},
    {month = 3, day = 8, names = "Dagmāra, Marga, Margita"},
    {month = 3, day = 9, names = "Ēvalds"},
    {month = 3, day = 10, names = "Silvija, Laimrota, Liliāna"},
    {month = 3, day = 11, names = "Konstantīns, Agita"},
    {month = 3, day = 12, names = "Aija, Aiva, Aivis"},
    {month = 3, day = 13, names = "Ernests, Balvis"},
    {month = 3, day = 14, names = "Matilde, Ulrika"},
    {month = 3, day = 15, names = "Amilda, Amalda, Imalda"},
    {month = 3, day = 16, names = "Guntis, Guntars, Guntris"},
    {month = 3, day = 17, names = "Ģertrūde, Gerda, Gerhards"},
    {month = 3, day = 18, names = "Ilona, Adelīna"},
    {month = 3, day = 19, names = "Jāzeps, Juzefa"},
    {month = 3, day = 20, names = "Made, Irbe"},
    {month = 3, day = 21, names = "Una, Unigunde, Dzelme, Benedikts, Benedikta"},
    {month = 3, day = 22, names = "Tamāra, Dziedra, Gabriels, Gabriela"},
    {month = 3, day = 23, names = "Mirdza, Žanete, Žanna"},
    {month = 3, day = 24, names = "Kazimirs, Izidors"},
    {month = 3, day = 25, names = "Māra, Mārīte, Marita, Mare, Ģedimins"},
    {month = 3, day = 26, names = "Eiženija, Ženija"},
    {month = 3, day = 27, names = "Gustavs, Gusts, Tālrīts, Saulis"},
    {month = 3, day = 28, names = "Gunta, Ginta, Gunda"},
    {month = 3, day = 29, names = "Aldonis, Agija"},
    {month = 3, day = 30, names = "Nanija, Ilgmārs"},
    {month = 3, day = 31, names = "Gvido, Atvars"},
    {month = 4, day = 1, names = "Dagnis, Dagne"},
    {month = 4, day = 2, names = "Irmgarde"},
    {month = 4, day = 3, names = "Daira, Dairis, Daiva, Daivis"},
    {month = 4, day = 4, names = "Valda, Herta, Ārvalda, Ārvalds, Ārvaldis"},
    {month = 4, day = 5, names = "Vija, Vidaga, Aivija"},
    {month = 4, day = 6, names = "Zinta, Vīlips, Filips, Dzinta, Dzintis"},
    {month = 4, day = 7, names = "Zina, Zinaīda, Helmuts"},
    {month = 4, day = 8, names = "Edgars, Danute, Dana, Dans"},
    {month = 4, day = 9, names = "Valērija, Žubīte, Alla"},
    {month = 4, day = 10, names = "Anita, Anitra, Zīle, Annika"},
    {month = 4, day = 11, names = "Hermanis, Vilmārs"},
    {month = 4, day = 12, names = "Jūlijs, Ainis"},
    {month = 4, day = 13, names = "Egils, Egīls, Nauris"},
    {month = 4, day = 14, names = "Strauja, Gudrīte"},
    {month = 4, day = 15, names = "Aelita, Gastons"},
    {month = 4, day = 16, names = "Mintauts, Alfs, Bernadeta"},
    {month = 4, day = 17, names = "Rūdolfs, Viviāna, Rūdis"},
    {month = 4, day = 18, names = "Laura, Jadviga"},
    {month = 4, day = 19, names = "Vēsma, Fanija"},
    {month = 4, day = 20, names = "Mirta, Ziedīte, Meija"},
    {month = 4, day = 21, names = "Marģers, Anastasija"},
    {month = 4, day = 22, names = "Armands, Armanda"},
    {month = 4, day = 23, names = "Jurģis, Juris, Georgs, Jurgita"},
    {month = 4, day = 24, names = "Visvaldis, Nameda, Ritvaldis, Ritums"},
    {month = 4, day = 25, names = "Līksma, Bārbala"},
    {month = 4, day = 26, names = "Alīna, Sandris, Rūsiņš"},
    {month = 4, day = 27, names = "Tāle, Raimonda, Raina, Klementīne"},
    {month = 4, day = 28, names = "Gundega, Terēze"},
    {month = 4, day = 29, names = "Vilnis, Raimonds, Laine"},
    {month = 4, day = 30, names = "Lilija, Liāna"},
    {month = 5, day = 1, names = "Ziedonis"},
    {month = 5, day = 2, names = "Zigmunds, Sigmunds, Zigismunds"},
    {month = 5, day = 3, names = "Gints, Uvis"},
    {month = 5, day = 4, names = "Vizbulīte, Viola, Vijolīte"},
    {month = 5, day = 5, names = "Ģirts, Ģederts"},
    {month = 5, day = 6, names = "Gaidis, Didzis"},
    {month = 5, day = 7, names = "Henriete, Henrijs, Jete, Enriko"},
    {month = 5, day = 8, names = "Staņislavs, Staņislava, Stefānija"},
    {month = 5, day = 9, names = "Klāvs, Einārs, Ervīns"},
    {month = 5, day = 10, names = "Maija, Paija"},
    {month = 5, day = 11, names = "Milda, Karmena, Manfreds"},
    {month = 5, day = 12, names = "Valija, Ināra, Ina, Inārs"},
    {month = 5, day = 13, names = "Irēna, Irīna, Ira, Iraīda"},
    {month = 5, day = 14, names = "Krišjānis, Elfa, Aivita, Elvita"},
    {month = 5, day = 15, names = "Sofija, Taiga, Airita, Arita"},
    {month = 5, day = 16, names = "Edvīns, Edijs"},
    {month = 5, day = 17, names = "Herberts, Dailis, Umberts"},
    {month = 5, day = 18, names = "Inese, Inesis, Ēriks"},
    {month = 5, day = 19, names = "Lita, Sibilla, Teika"},
    {month = 5, day = 20, names = "Venta, Salvis, Selva"},
    {month = 5, day = 21, names = "Ernestīne, Ingmārs, Akvelīna"},
    {month = 5, day = 22, names = "Emīlija. Visu neparasto un kalendāros neierakstīto vārdu diena"},
    {month = 5, day = 23, names = "Leontīne, Leokādija, Lonija, Ligija"},
    {month = 5, day = 24, names = "Ilvija, Marlēna, Ziedone"},
    {month = 5, day = 25, names = "Anšlavs, Junora"},
    {month = 5, day = 26, names = "Edvards, Edvarts, Eduards, Varis"},
    {month = 5, day = 27, names = "Dzidra, Gunita, Loreta, Dzidris"},
    {month = 5, day = 28, names = "Vilis, Vilhelms"},
    {month = 5, day = 29, names = "Maksis, Maksims, Raivis, Raivo"},
    {month = 5, day = 30, names = "Vitolds, Lolita, Letīcija"},
    {month = 5, day = 31, names = "Alīda, Jūsma"},
    {month = 6, day = 1, names = "Biruta, Mairita, Bernedīne"},
    {month = 6, day = 2, names = "Lība, Emma"},
    {month = 6, day = 3, names = "Inta, Ineta, Intra"},
    {month = 6, day = 4, names = "Elfrīda, Sintija, Sindija"},
    {month = 6, day = 5, names = "Igors, Margots, Ingvars"},
    {month = 6, day = 6, names = "Ingrīda, Ardis"},
    {month = 6, day = 7, names = "Gaida, Arnis, Arno"},
    {month = 6, day = 8, names = "Frīdis, Frīda, Mundra"},
    {month = 6, day = 9, names = "Ligita, Gita"},
    {month = 6, day = 10, names = "Malva, Anatols, Anatolijs"},
    {month = 6, day = 11, names = "Ingus, Mairis, Vidvuds"},
    {month = 6, day = 12, names = "Nora, Lenora, Ija"},
    {month = 6, day = 13, names = "Zigfrīds, Ainārs, Uva"},
    {month = 6, day = 14, names = "Tija, Saiva, Sentis, Santis, Saivis"},
    {month = 6, day = 15, names = "Baņuta, Žermēna, Vilija, Vits"},
    {month = 6, day = 16, names = "Justīne, Juta"},
    {month = 6, day = 17, names = "Artūrs, Artis"},
    {month = 6, day = 18, names = "Alberts, Madis"},
    {month = 6, day = 19, names = "Viktors, Nils"},
    {month = 6, day = 20, names = "Rasma, Rasa, Maira"},
    {month = 6, day = 21, names = "Emīls, Egita, Monvīds"},
    {month = 6, day = 22, names = "Ludmila, Laimdots, Laimiņš"},
    {month = 6, day = 23, names = "Līga"},
    {month = 6, day = 24, names = "Jānis"},
    {month = 6, day = 25, names = "Milija, Maiga"},
    {month = 6, day = 26, names = "Ausma, Inguna, Ingūna, Inguns, Ausmis"},
    {month = 6, day = 27, names = "Malvīne, Malvis"},
    {month = 6, day = 28, names = "Viesturs, Kitija, Viestards"},
    {month = 6, day = 29, names = "Pēteris, Pāvils, Pauls, Paulis"},
    {month = 6, day = 30, names = "Tālivaldis, Mareks"},
    {month = 7, day = 1, names = "Imants, Rimants, Ingars, Intars"},
    {month = 7, day = 2, names = "Lauma, Ilvars, Halina"},
    {month = 7, day = 3, names = "Benita, Everita, Verita, Emerita"},
    {month = 7, day = 4, names = "Ulvis, Uldis, Sandis, Sandijs"},
    {month = 7, day = 5, names = "Andžs, Andžejs, Edīte, Esmeralda"},
    {month = 7, day = 6, names = "Anrijs, Arkādijs"},
    {month = 7, day = 7, names = "Alda, Maruta"},
    {month = 7, day = 8, names = "Antra, Adele, Ada"},
    {month = 7, day = 9, names = "Zaiga, Asne, Asna"},
    {month = 7, day = 10, names = "Lija, Olīvija, Olivers, Odrija"},
    {month = 7, day = 11, names = "Leonora, Svens"},
    {month = 7, day = 12, names = "Indriķis, Ints, Namejs"},
    {month = 7, day = 13, names = "Margrieta, Margarita"},
    {month = 7, day = 14, names = "Oskars, Ritvars, Anvars"},
    {month = 7, day = 15, names = "Egons, Egmonts, Egija, Henriks, Heinrihs"},
    {month = 7, day = 16, names = "Hermīne, Estere, Liepa"},
    {month = 7, day = 17, names = "Aleksis, Aleksejs, Alekss"},
    {month = 7, day = 18, names = "Rozālija, Roze"},
    {month = 7, day = 19, names = "Jautrīte, Kamila, Digna, Sāra"},
    {month = 7, day = 20, names = "Ritma, Ramona"},
    {month = 7, day = 21, names = "Meldra, Meldris, Melisa"},
    {month = 7, day = 22, names = "Marija, Marika, Marina"},
    {month = 7, day = 23, names = "Magda, Magone, Mērija, Magdalēna"},
    {month = 7, day = 24, names = "Kristīne, Kristīna, Krista, Kristiāna, Kristiāns"},
    {month = 7, day = 25, names = "Jēkabs, Žaklīna"},
    {month = 7, day = 26, names = "Anna, Ance, Annija"},
    {month = 7, day = 27, names = "Marta, Dita, Dite"},
    {month = 7, day = 28, names = "Cecīlija, Cilda"},
    {month = 7, day = 29, names = "Edmunds, Edžus, Vidmants"},
    {month = 7, day = 30, names = "Valters, Renārs, Regnārs"},
    {month = 7, day = 31, names = "Rūta, Ruta, Angelika, Sigita"},
    {month = 8, day = 1, names = "Albīns, Albīna"},
    {month = 8, day = 2, names = "Normunds, Stefans"},
    {month = 8, day = 3, names = "Augusts"},
    {month = 8, day = 4, names = "Romāns, Romualds, Romualda"},
    {month = 8, day = 5, names = "Osvalds, Arvils"},
    {month = 8, day = 6, names = "Askolds, Aisma"},
    {month = 8, day = 7, names = "Alfrēds, Madars, Fredis"},
    {month = 8, day = 8, names = "Mudīte, Vladislavs, Vladislava"},
    {month = 8, day = 9, names = "Madara, Genoveva, Genovefa"},
    {month = 8, day = 10, names = "Brencis, Audris, Inuta, Audra"},
    {month = 8, day = 11, names = "Olga, Zita, Liega, Zigita"},
    {month = 8, day = 12, names = "Vizma, Klāra"},
    {month = 8, day = 13, names = "Elvīra, Velga, Rēzija"},
    {month = 8, day = 14, names = "Zelma, Zemgus, Virma"},
    {month = 8, day = 15, names = "Zenta, Dzelde, Zelda"},
    {month = 8, day = 16, names = "Astra, Astrīda"},
    {month = 8, day = 17, names = "Vineta, Oļegs"},
    {month = 8, day = 18, names = "Liene, Helēna, Elena, Ellena, Liena"},
    {month = 8, day = 19, names = "Melānija, Imanta"},
    {month = 8, day = 20, names = "Bernhards, Boriss, Rojs"},
    {month = 8, day = 21, names = "Janīna, Linda"},
    {month = 8, day = 22, names = "Rudīte, Everts"},
    {month = 8, day = 23, names = "Vitālijs, Ralfs, Valgudis"},
    {month = 8, day = 24, names = "Bērtulis, Boļeslavs"},
    {month = 8, day = 25, names = "Ludvigs, Ludis, Ivonna, Patrīcija, Patriks"},
    {month = 8, day = 26, names = "Natālija, Tālija, Broņislavs, Broņislava"},
    {month = 8, day = 27, names = "Žanis, Jorens, Alens"},
    {month = 8, day = 28, names = "Auguste, Guste"},
    {month = 8, day = 29, names = "Armīns, Vismants, Aiga"},
    {month = 8, day = 30, names = "Alvis, Jolanta, Samanta"},
    {month = 8, day = 31, names = "Vilma, Aigars"},
    {month = 9, day = 1, names = "Ilmārs, Iluta, Austrums"},
    {month = 9, day = 2, names = "Elīza, Lizete, Zete"},
    {month = 9, day = 3, names = "Berta, Bella"},
    {month = 9, day = 4, names = "Dzintra, Dzintara, Dzintars"},
    {month = 9, day = 5, names = "Klaudija, Persijs, Vaida"},
    {month = 9, day = 6, names = "Maigonis, Magnuss, Mariuss"},
    {month = 9, day = 7, names = "Regīna, Ermīns"},
    {month = 9, day = 8, names = "Ilga"},
    {month = 9, day = 9, names = "Bruno, Telma"},
    {month = 9, day = 10, names = "Jausma, Albertīne"},
    {month = 9, day = 11, names = "Signe, Signija"},
    {month = 9, day = 12, names = "Erna, Evita, Eva"},
    {month = 9, day = 13, names = "Iza, Izabella"},
    {month = 9, day = 14, names = "Sanita, Santa, Sanda, Sanija, Sandija"},
    {month = 9, day = 15, names = "Sandra, Gunvaldis, Gunvaris, Sondra"},
    {month = 9, day = 16, names = "Asja, Asnate, Dāgs"},
    {month = 9, day = 17, names = "Vera, Vaira, Vairis, Vaiva"},
    {month = 9, day = 18, names = "Liesma, Elita, Alita"},
    {month = 9, day = 19, names = "Verners, Muntis"},
    {month = 9, day = 20, names = "Guntra, Ginters, Marianna"},
    {month = 9, day = 21, names = "Modris, Matīss, Mariss"},
    {month = 9, day = 22, names = "Māris, Mārica, Maigurs"},
    {month = 9, day = 23, names = "Vanda, Veneranda, Venija"},
    {month = 9, day = 24, names = "Agris, Agrita"},
    {month = 9, day = 25, names = "Rodrigo, Rauls"},
    {month = 9, day = 26, names = "Gundars, Kurts, Knuts"},
    {month = 9, day = 27, names = "Ādolfs, Ilgonis"},
    {month = 9, day = 28, names = "Sergejs, Svetlana, Lana"},
    {month = 9, day = 29, names = "Miķelis, Mikus, Miks, Mihails, Jumis"},
    {month = 9, day = 30, names = "Elma, Menarda, Elna"},
    {month = 10, day = 1, names = "Zanda, Lāsma, Zandis"},
    {month = 10, day = 2, names = "Ilma, Skaidris"},
    {month = 10, day = 3, names = "Elza, Ilizana"},
    {month = 10, day = 4, names = "Modra, Francis, Dmitrijs"},
    {month = 10, day = 5, names = "Amālija, Amēlija"},
    {month = 10, day = 6, names = "Monika, Zilgma, Zilga"},
    {month = 10, day = 7, names = "Daumants, Druvvaldis"},
    {month = 10, day = 8, names = "Aina, Anete"},
    {month = 10, day = 9, names = "Elga, Helga, Elgars"},
    {month = 10, day = 10, names = "Arvīds, Arvis, Druvis"},
    {month = 10, day = 11, names = "Monta, Tince, Silva"},
    {month = 10, day = 12, names = "Valfrīds, Kira"},
    {month = 10, day = 13, names = "Irma, Mirga"},
    {month = 10, day = 14, names = "Vilhelmīne, Minna"},
    {month = 10, day = 15, names = "Eda, Hedviga, Helvijs"},
    {month = 10, day = 16, names = "Daiga, Dinija, Dinārs"},
    {month = 10, day = 17, names = "Gaits, Karīna, Gaitis"},
    {month = 10, day = 18, names = "Rolands, Rolanda, Ronalds, Erlends, Lūkass"},
    {month = 10, day = 19, names = "Elīna, Drosma, Drosmis"},
    {month = 10, day = 20, names = "Leonīds, Leonīda"},
    {month = 10, day = 21, names = "Urzula, Severīns"},
    {month = 10, day = 22, names = "Īrisa, Irīda, Airisa"},
    {month = 10, day = 23, names = "Daina, Dainis, Dainida"},
    {month = 10, day = 24, names = "Renāte, Modrīte, Mudrīte"},
    {month = 10, day = 25, names = "Beāte, Beatrise"},
    {month = 10, day = 26, names = "Amanda, Kaiva, Amanta"},
    {month = 10, day = 27, names = "Lilita, Irita, Ita"},
    {month = 10, day = 28, names = "Ņina, Ninona, Antoņina, Oksana"},
    {month = 10, day = 29, names = "Laimonis, Elvijs, Elva, Elvis, Laimis"},
    {month = 10, day = 30, names = "Nadīna, Ulla, Adīna"},
    {month = 10, day = 31, names = "Valts, Rinalds, Rinalda"},
    {month = 11, day = 1, names = "Ikars"},
    {month = 11, day = 2, names = "Vivita, Dzīle, Viva"},
    {month = 11, day = 3, names = "Ērika, Dagnija"},
    {month = 11, day = 4, names = "Atis, Otomārs, Oto"},
    {month = 11, day = 5, names = "Šarlote, Lote"},
    {month = 11, day = 6, names = "Linards, Leons, Leo, Leonards, Leonarda"},
    {month = 11, day = 7, names = "Helma, Lotārs, Pērle"},
    {month = 11, day = 8, names = "Aleksandra, Agra"},
    {month = 11, day = 9, names = "Teodors"},
    {month = 11, day = 10, names = "Mārtiņš, Mārcis, Markuss, Marks"},
    {month = 11, day = 11, names = "Ojārs, Rainers, Nellija"},
    {month = 11, day = 12, names = "Kaija, Kornēlija"},
    {month = 11, day = 13, names = "Eižens, Jevgeņijs, Jevgeņija"},
    {month = 11, day = 14, names = "Fricis, Vikentijs, Vincents"},
    {month = 11, day = 15, names = "Leopolds, Undīne, Unda"},
    {month = 11, day = 16, names = "Banga, Glorija"},
    {month = 11, day = 17, names = "Hugo, Uga, Uģis"},
    {month = 11, day = 18, names = "Aleksandrs, Doloresa, Brīve"},
    {month = 11, day = 19, names = "Elizabete, Liza, Līze, Betija"},
    {month = 11, day = 20, names = "Anda, Andīna, Vigo"},
    {month = 11, day = 21, names = "Zeltīte, Andis"},
    {month = 11, day = 22, names = "Aldis, Alfons, Aldris"},
    {month = 11, day = 23, names = "Zigrīda, Zigfrīda, Zigrīds"},
    {month = 11, day = 24, names = "Velta, Velda"},
    {month = 11, day = 25, names = "Katrīna, Kate, Kadrija, Trīne, Katrīne"},
    {month = 11, day = 26, names = "Konrāds, Sebastians"},
    {month = 11, day = 27, names = "Lauris, Norberts"},
    {month = 11, day = 28, names = "Rita, Vita, Olita"},
    {month = 11, day = 29, names = "Ignats, Virgīnija"},
    {month = 11, day = 30, names = "Andrievs, Andrejs, Andris"},
    {month = 12, day = 1, names = "Arnolds, Emanuels"},
    {month = 12, day = 2, names = "Meta, Sniedze"},
    {month = 12, day = 3, names = "Evija, Raita, Jogita, Ako"},
    {month = 12, day = 4, names = "Baiba, Barbara, Barba"},
    {month = 12, day = 5, names = "Sabīne, Sarma, Klaudijs"},
    {month = 12, day = 6, names = "Nikolajs, Niklāvs, Niks, Nikola"},
    {month = 12, day = 7, names = "Antonija, Anta, Dzirkstīte"},
    {month = 12, day = 8, names = "Gunārs, Vladimirs, Gunis"},
    {month = 12, day = 9, names = "Tabita, Sarmīte"},
    {month = 12, day = 10, names = "Guna, Judīte"},
    {month = 12, day = 11, names = "Voldemārs, Valdemārs, Valdis"},
    {month = 12, day = 12, names = "Otīlija, Iveta"},
    {month = 12, day = 13, names = "Lūcija, Veldze"},
    {month = 12, day = 14, names = "Auseklis, Gaisma"},
    {month = 12, day = 15, names = "Johanna, Hanna, Jana"},
    {month = 12, day = 16, names = "Alvīne"},
    {month = 12, day = 17, names = "Hilda, Teiksma"},
    {month = 12, day = 18, names = "Kristaps, Kristofers, Krists, Klinta, Kristers"},
    {month = 12, day = 19, names = "Lelde, Sarmis"},
    {month = 12, day = 20, names = "Arta, Minjona"},
    {month = 12, day = 21, names = "Toms, Tomass, Saulcerīte"},
    {month = 12, day = 22, names = "Saulvedis, Saule"},
    {month = 12, day = 23, names = "Viktorija, Balva"},
    {month = 12, day = 24, names = "Ādams, Ieva"},
    {month = 12, day = 25, names = "Stella, Larisa"},
    {month = 12, day = 26, names = "Dainuvīte, Gija, Megija"},
    {month = 12, day = 27, names = "Elmārs, Inita, Helmārs"},
    {month = 12, day = 28, names = "Inga, Ivita, Irvita, Ingeborga"},
    {month = 12, day = 29, names = "Solveiga, Ilgona"},
    {month = 12, day = 30, names = "Dāvids, Dāvis, Dāniels, Daniela, Daniels"},
    {month = 12, day = 31, names = "Silvestrs, Silvis, Kalvis"},
}
