// Auto-generated from VVC (Valsts valodas centrs) official Latvian name days
const Data = struct {
    month: u8,
    day: u8,
    names: []const u8,
};

pub const entries = [_]Data{
    Data{ .month = 1, .day = 1, .names = "Laimnesis, Solvita, Solvija" },
    Data{ .month = 1, .day = 2, .names = "Indulis, Ivo, Iva, Ivis" },
    Data{ .month = 1, .day = 3, .names = "Miervaldis, Miervalda, Ringolds" },
    Data{ .month = 1, .day = 4, .names = "Spodra, Ilva, Ilvita" },
    Data{ .month = 1, .day = 5, .names = "Sīmanis, Zintis" },
    Data{ .month = 1, .day = 6, .names = "Spulga, Arnita" },
    Data{ .month = 1, .day = 7, .names = "Rota, Zigmārs, Juliāns, Digmārs" },
    Data{ .month = 1, .day = 8, .names = "Gatis, Ivanda" },
    Data{ .month = 1, .day = 9, .names = "Kaspars, Aksels, Alta" },
    Data{ .month = 1, .day = 10, .names = "Tatjana, Dorisa" },
    Data{ .month = 1, .day = 11, .names = "Smaida, Franciska" },
    Data{ .month = 1, .day = 12, .names = "Reinis, Reina, Reinholds, Renāts" },
    Data{ .month = 1, .day = 13, .names = "Harijs, Ārijs, Āris, Aira" },
    Data{ .month = 1, .day = 14, .names = "Roberts, Roberta, Raitis, Raits" },
    Data{ .month = 1, .day = 15, .names = "Fēlikss, Felicita" },
    Data{ .month = 1, .day = 16, .names = "Lidija, Lida" },
    Data{ .month = 1, .day = 17, .names = "Tenis, Dravis" },
    Data{ .month = 1, .day = 18, .names = "Antons, Antis, Antonijs" },
    Data{ .month = 1, .day = 19, .names = "Andulis, Alnis" },
    Data{ .month = 1, .day = 20, .names = "Oļģerts, Orests, Aļģirds, Aļģis" },
    Data{ .month = 1, .day = 21, .names = "Agnese, Agnija, Agne" },
    Data{ .month = 1, .day = 22, .names = "Austris" },
    Data{ .month = 1, .day = 23, .names = "Grieta, Strauta, Rebeka" },
    Data{ .month = 1, .day = 24, .names = "Krišs, Ksenija, Eglons, Egle" },
    Data{ .month = 1, .day = 25, .names = "Zigurds, Sigurds, Sigvards" },
    Data{ .month = 1, .day = 26, .names = "Ansis, Agnis, Agneta" },
    Data{ .month = 1, .day = 27, .names = "Ilze, Ildze, Izolde" },
    Data{ .month = 1, .day = 28, .names = "Kārlis, Spodris" },
    Data{ .month = 1, .day = 29, .names = "Aivars, Valērijs, Bille" },
    Data{ .month = 1, .day = 30, .names = "Tīna, Valentīna, Pārsla" },
    Data{ .month = 1, .day = 31, .names = "Tekla, Violeta" },
    Data{ .month = 2, .day = 1, .names = "Brigita, Indra, Indars, Indris" },
    Data{ .month = 2, .day = 2, .names = "Spīdola, Sonora" },
    Data{ .month = 2, .day = 3, .names = "Aīda, Ida, Vida" },
    Data{ .month = 2, .day = 4, .names = "Daila, Veronika, Dominiks" },
    Data{ .month = 2, .day = 5, .names = "Agate, Selga, Silga, Sinilga" },
    Data{ .month = 2, .day = 6, .names = "Dace, Dārta, Dora, Daris" },
    Data{ .month = 2, .day = 7, .names = "Nelda, Rihards, Ričards, Rišards" },
    Data{ .month = 2, .day = 8, .names = "Aldona, Česlavs" },
    Data{ .month = 2, .day = 9, .names = "Simona, Apolonija" },
    Data{ .month = 2, .day = 10, .names = "Paulīne, Paula, Jasmīna" },
    Data{ .month = 2, .day = 11, .names = "Laima, Laimdota" },
    Data{ .month = 2, .day = 12, .names = "Karlīna, Līna" },
    Data{ .month = 2, .day = 13, .names = "Malda, Melita" },
    Data{ .month = 2, .day = 14, .names = "Valentīns" },
    Data{ .month = 2, .day = 15, .names = "Alvils, Olafs, Aloizs, Olavs" },
    Data{ .month = 2, .day = 16, .names = "Jūlija, Džuljeta" },
    Data{ .month = 2, .day = 17, .names = "Donats, Konstance" },
    Data{ .month = 2, .day = 18, .names = "Kora, Kintija" },
    Data{ .month = 2, .day = 19, .names = "Zane, Zuzanna" },
    Data{ .month = 2, .day = 20, .names = "Vitauts, Smuidra, Smuidris" },
    Data{ .month = 2, .day = 21, .names = "Eleonora, Ariadne" },
    Data{ .month = 2, .day = 22, .names = "Ārija, Rigonda, Adrians, Adriāna, Adrija" },
    Data{ .month = 2, .day = 23, .names = "Haralds, Almants" },
    Data{ .month = 2, .day = 24, .names = "Diāna, Dina, Dins" },
    Data{ .month = 2, .day = 25, .names = "Alma, Annemarija" },
    Data{ .month = 2, .day = 26, .names = "Evelīna, Aurēlija, Mētra" },
    Data{ .month = 2, .day = 27, .names = "Līvija, Līva, Andra" },
    Data{ .month = 2, .day = 28, .names = "Skaidrīte, Justs, Skaidra" },
    Data{ .month = 3, .day = 1, .names = "Ivars, Ilgvars" },
    Data{ .month = 3, .day = 2, .names = "Lavīze, Luīze, Laila" },
    Data{ .month = 3, .day = 3, .names = "Tālis, Tālavs, Marts" },
    Data{ .month = 3, .day = 4, .names = "Alise, Auce, Enija" },
    Data{ .month = 3, .day = 5, .names = "Austra, Aurora, Aurika" },
    Data{ .month = 3, .day = 6, .names = "Vents, Centis, Gotfrīds" },
    Data{ .month = 3, .day = 7, .names = "Ella, Elmīra" },
    Data{ .month = 3, .day = 8, .names = "Dagmāra, Marga, Margita" },
    Data{ .month = 3, .day = 9, .names = "Ēvalds" },
    Data{ .month = 3, .day = 10, .names = "Silvija, Laimrota, Liliāna" },
    Data{ .month = 3, .day = 11, .names = "Konstantīns, Agita" },
    Data{ .month = 3, .day = 12, .names = "Aija, Aiva, Aivis" },
    Data{ .month = 3, .day = 13, .names = "Ernests, Balvis" },
    Data{ .month = 3, .day = 14, .names = "Matilde, Ulrika" },
    Data{ .month = 3, .day = 15, .names = "Amilda, Amalda, Imalda" },
    Data{ .month = 3, .day = 16, .names = "Guntis, Guntars, Guntris" },
    Data{ .month = 3, .day = 17, .names = "Ģertrūde, Gerda, Gerhards" },
    Data{ .month = 3, .day = 18, .names = "Ilona, Adelīna" },
    Data{ .month = 3, .day = 19, .names = "Jāzeps, Juzefa" },
    Data{ .month = 3, .day = 20, .names = "Made, Irbe" },
    Data{ .month = 3, .day = 21, .names = "Una, Unigunde, Dzelme, Benedikts, Benedikta" },
    Data{ .month = 3, .day = 22, .names = "Tamāra, Dziedra, Gabriels, Gabriela" },
    Data{ .month = 3, .day = 23, .names = "Mirdza, Žanete, Žanna" },
    Data{ .month = 3, .day = 24, .names = "Kazimirs, Izidors" },
    Data{ .month = 3, .day = 25, .names = "Māra, Mārīte, Marita, Mare, Ģedimins" },
    Data{ .month = 3, .day = 26, .names = "Eiženija, Ženija" },
    Data{ .month = 3, .day = 27, .names = "Gustavs, Gusts, Tālrīts, Saulis" },
    Data{ .month = 3, .day = 28, .names = "Gunta, Ginta, Gunda" },
    Data{ .month = 3, .day = 29, .names = "Aldonis, Agija" },
    Data{ .month = 3, .day = 30, .names = "Nanija, Ilgmārs" },
    Data{ .month = 3, .day = 31, .names = "Gvido, Atvars" },
    Data{ .month = 4, .day = 1, .names = "Dagnis, Dagne" },
    Data{ .month = 4, .day = 2, .names = "Irmgarde" },
    Data{ .month = 4, .day = 3, .names = "Daira, Dairis, Daiva, Daivis" },
    Data{ .month = 4, .day = 4, .names = "Valda, Herta, Ārvalda, Ārvalds, Ārvaldis" },
    Data{ .month = 4, .day = 5, .names = "Vija, Vidaga, Aivija" },
    Data{ .month = 4, .day = 6, .names = "Zinta, Vīlips, Filips, Dzinta, Dzintis" },
    Data{ .month = 4, .day = 7, .names = "Zina, Zinaīda, Helmuts" },
    Data{ .month = 4, .day = 8, .names = "Edgars, Danute, Dana, Dans" },
    Data{ .month = 4, .day = 9, .names = "Valērija, Žubīte, Alla" },
    Data{ .month = 4, .day = 10, .names = "Anita, Anitra, Zīle, Annika" },
    Data{ .month = 4, .day = 11, .names = "Hermanis, Vilmārs" },
    Data{ .month = 4, .day = 12, .names = "Jūlijs, Ainis" },
    Data{ .month = 4, .day = 13, .names = "Egils, Egīls, Nauris" },
    Data{ .month = 4, .day = 14, .names = "Strauja, Gudrīte" },
    Data{ .month = 4, .day = 15, .names = "Aelita, Gastons" },
    Data{ .month = 4, .day = 16, .names = "Mintauts, Alfs, Bernadeta" },
    Data{ .month = 4, .day = 17, .names = "Rūdolfs, Viviāna, Rūdis" },
    Data{ .month = 4, .day = 18, .names = "Laura, Jadviga" },
    Data{ .month = 4, .day = 19, .names = "Vēsma, Fanija" },
    Data{ .month = 4, .day = 20, .names = "Mirta, Ziedīte, Meija" },
    Data{ .month = 4, .day = 21, .names = "Marģers, Anastasija" },
    Data{ .month = 4, .day = 22, .names = "Armands, Armanda" },
    Data{ .month = 4, .day = 23, .names = "Jurģis, Juris, Georgs, Jurgita" },
    Data{ .month = 4, .day = 24, .names = "Visvaldis, Nameda, Ritvaldis, Ritums" },
    Data{ .month = 4, .day = 25, .names = "Līksma, Bārbala" },
    Data{ .month = 4, .day = 26, .names = "Alīna, Sandris, Rūsiņš" },
    Data{ .month = 4, .day = 27, .names = "Tāle, Raimonda, Raina, Klementīne" },
    Data{ .month = 4, .day = 28, .names = "Gundega, Terēze" },
    Data{ .month = 4, .day = 29, .names = "Vilnis, Raimonds, Laine" },
    Data{ .month = 4, .day = 30, .names = "Lilija, Liāna" },
    Data{ .month = 5, .day = 1, .names = "Ziedonis" },
    Data{ .month = 5, .day = 2, .names = "Zigmunds, Sigmunds, Zigismunds" },
    Data{ .month = 5, .day = 3, .names = "Gints, Uvis" },
    Data{ .month = 5, .day = 4, .names = "Vizbulīte, Viola, Vijolīte" },
    Data{ .month = 5, .day = 5, .names = "Ģirts, Ģederts" },
    Data{ .month = 5, .day = 6, .names = "Gaidis, Didzis" },
    Data{ .month = 5, .day = 7, .names = "Henriete, Henrijs, Jete, Enriko" },
    Data{ .month = 5, .day = 8, .names = "Staņislavs, Staņislava, Stefānija" },
    Data{ .month = 5, .day = 9, .names = "Klāvs, Einārs, Ervīns" },
    Data{ .month = 5, .day = 10, .names = "Maija, Paija" },
    Data{ .month = 5, .day = 11, .names = "Milda, Karmena, Manfreds" },
    Data{ .month = 5, .day = 12, .names = "Valija, Ināra, Ina, Inārs" },
    Data{ .month = 5, .day = 13, .names = "Irēna, Irīna, Ira, Iraīda" },
    Data{ .month = 5, .day = 14, .names = "Krišjānis, Elfa, Aivita, Elvita" },
    Data{ .month = 5, .day = 15, .names = "Sofija, Taiga, Airita, Arita" },
    Data{ .month = 5, .day = 16, .names = "Edvīns, Edijs" },
    Data{ .month = 5, .day = 17, .names = "Herberts, Dailis, Umberts" },
    Data{ .month = 5, .day = 18, .names = "Inese, Inesis, Ēriks" },
    Data{ .month = 5, .day = 19, .names = "Lita, Sibilla, Teika" },
    Data{ .month = 5, .day = 20, .names = "Venta, Salvis, Selva" },
    Data{ .month = 5, .day = 21, .names = "Ernestīne, Ingmārs, Akvelīna" },
    Data{ .month = 5, .day = 22, .names = "Emīlija. Visu neparasto un kalendāros neierakstīto vārdu diena" },
    Data{ .month = 5, .day = 23, .names = "Leontīne, Leokādija, Lonija, Ligija" },
    Data{ .month = 5, .day = 24, .names = "Ilvija, Marlēna, Ziedone" },
    Data{ .month = 5, .day = 25, .names = "Anšlavs, Junora" },
    Data{ .month = 5, .day = 26, .names = "Edvards, Edvarts, Eduards, Varis" },
    Data{ .month = 5, .day = 27, .names = "Dzidra, Gunita, Loreta, Dzidris" },
    Data{ .month = 5, .day = 28, .names = "Vilis, Vilhelms" },
    Data{ .month = 5, .day = 29, .names = "Maksis, Maksims, Raivis, Raivo" },
    Data{ .month = 5, .day = 30, .names = "Vitolds, Lolita, Letīcija" },
    Data{ .month = 5, .day = 31, .names = "Alīda, Jūsma" },
    Data{ .month = 6, .day = 1, .names = "Biruta, Mairita, Bernedīne" },
    Data{ .month = 6, .day = 2, .names = "Lība, Emma" },
    Data{ .month = 6, .day = 3, .names = "Inta, Ineta, Intra" },
    Data{ .month = 6, .day = 4, .names = "Elfrīda, Sintija, Sindija" },
    Data{ .month = 6, .day = 5, .names = "Igors, Margots, Ingvars" },
    Data{ .month = 6, .day = 6, .names = "Ingrīda, Ardis" },
    Data{ .month = 6, .day = 7, .names = "Gaida, Arnis, Arno" },
    Data{ .month = 6, .day = 8, .names = "Frīdis, Frīda, Mundra" },
    Data{ .month = 6, .day = 9, .names = "Ligita, Gita" },
    Data{ .month = 6, .day = 10, .names = "Malva, Anatols, Anatolijs" },
    Data{ .month = 6, .day = 11, .names = "Ingus, Mairis, Vidvuds" },
    Data{ .month = 6, .day = 12, .names = "Nora, Lenora, Ija" },
    Data{ .month = 6, .day = 13, .names = "Zigfrīds, Ainārs, Uva" },
    Data{ .month = 6, .day = 14, .names = "Tija, Saiva, Sentis, Santis, Saivis" },
    Data{ .month = 6, .day = 15, .names = "Baņuta, Žermēna, Vilija, Vits" },
    Data{ .month = 6, .day = 16, .names = "Justīne, Juta" },
    Data{ .month = 6, .day = 17, .names = "Artūrs, Artis" },
    Data{ .month = 6, .day = 18, .names = "Alberts, Madis" },
    Data{ .month = 6, .day = 19, .names = "Viktors, Nils" },
    Data{ .month = 6, .day = 20, .names = "Rasma, Rasa, Maira" },
    Data{ .month = 6, .day = 21, .names = "Emīls, Egita, Monvīds" },
    Data{ .month = 6, .day = 22, .names = "Ludmila, Laimdots, Laimiņš" },
    Data{ .month = 6, .day = 23, .names = "Līga" },
    Data{ .month = 6, .day = 24, .names = "Jānis" },
    Data{ .month = 6, .day = 25, .names = "Milija, Maiga" },
    Data{ .month = 6, .day = 26, .names = "Ausma, Inguna, Ingūna, Inguns, Ausmis" },
    Data{ .month = 6, .day = 27, .names = "Malvīne, Malvis" },
    Data{ .month = 6, .day = 28, .names = "Viesturs, Kitija, Viestards" },
    Data{ .month = 6, .day = 29, .names = "Pēteris, Pāvils, Pauls, Paulis" },
    Data{ .month = 6, .day = 30, .names = "Tālivaldis, Mareks" },
    Data{ .month = 7, .day = 1, .names = "Imants, Rimants, Ingars, Intars" },
    Data{ .month = 7, .day = 2, .names = "Lauma, Ilvars, Halina" },
    Data{ .month = 7, .day = 3, .names = "Benita, Everita, Verita, Emerita" },
    Data{ .month = 7, .day = 4, .names = "Ulvis, Uldis, Sandis, Sandijs" },
    Data{ .month = 7, .day = 5, .names = "Andžs, Andžejs, Edīte, Esmeralda" },
    Data{ .month = 7, .day = 6, .names = "Anrijs, Arkādijs" },
    Data{ .month = 7, .day = 7, .names = "Alda, Maruta" },
    Data{ .month = 7, .day = 8, .names = "Antra, Adele, Ada" },
    Data{ .month = 7, .day = 9, .names = "Zaiga, Asne, Asna" },
    Data{ .month = 7, .day = 10, .names = "Lija, Olīvija, Olivers, Odrija" },
    Data{ .month = 7, .day = 11, .names = "Leonora, Svens" },
    Data{ .month = 7, .day = 12, .names = "Indriķis, Ints, Namejs" },
    Data{ .month = 7, .day = 13, .names = "Margrieta, Margarita" },
    Data{ .month = 7, .day = 14, .names = "Oskars, Ritvars, Anvars" },
    Data{ .month = 7, .day = 15, .names = "Egons, Egmonts, Egija, Henriks, Heinrihs" },
    Data{ .month = 7, .day = 16, .names = "Hermīne, Estere, Liepa" },
    Data{ .month = 7, .day = 17, .names = "Aleksis, Aleksejs, Alekss" },
    Data{ .month = 7, .day = 18, .names = "Rozālija, Roze" },
    Data{ .month = 7, .day = 19, .names = "Jautrīte, Kamila, Digna, Sāra" },
    Data{ .month = 7, .day = 20, .names = "Ritma, Ramona" },
    Data{ .month = 7, .day = 21, .names = "Meldra, Meldris, Melisa" },
    Data{ .month = 7, .day = 22, .names = "Marija, Marika, Marina" },
    Data{ .month = 7, .day = 23, .names = "Magda, Magone, Mērija, Magdalēna" },
    Data{ .month = 7, .day = 24, .names = "Kristīne, Kristīna, Krista, Kristiāna, Kristiāns" },
    Data{ .month = 7, .day = 25, .names = "Jēkabs, Žaklīna" },
    Data{ .month = 7, .day = 26, .names = "Anna, Ance, Annija" },
    Data{ .month = 7, .day = 27, .names = "Marta, Dita, Dite" },
    Data{ .month = 7, .day = 28, .names = "Cecīlija, Cilda" },
    Data{ .month = 7, .day = 29, .names = "Edmunds, Edžus, Vidmants" },
    Data{ .month = 7, .day = 30, .names = "Valters, Renārs, Regnārs" },
    Data{ .month = 7, .day = 31, .names = "Rūta, Ruta, Angelika, Sigita" },
    Data{ .month = 8, .day = 1, .names = "Albīns, Albīna" },
    Data{ .month = 8, .day = 2, .names = "Normunds, Stefans" },
    Data{ .month = 8, .day = 3, .names = "Augusts" },
    Data{ .month = 8, .day = 4, .names = "Romāns, Romualds, Romualda" },
    Data{ .month = 8, .day = 5, .names = "Osvalds, Arvils" },
    Data{ .month = 8, .day = 6, .names = "Askolds, Aisma" },
    Data{ .month = 8, .day = 7, .names = "Alfrēds, Madars, Fredis" },
    Data{ .month = 8, .day = 8, .names = "Mudīte, Vladislavs, Vladislava" },
    Data{ .month = 8, .day = 9, .names = "Madara, Genoveva, Genovefa" },
    Data{ .month = 8, .day = 10, .names = "Brencis, Audris, Inuta, Audra" },
    Data{ .month = 8, .day = 11, .names = "Olga, Zita, Liega, Zigita" },
    Data{ .month = 8, .day = 12, .names = "Vizma, Klāra" },
    Data{ .month = 8, .day = 13, .names = "Elvīra, Velga, Rēzija" },
    Data{ .month = 8, .day = 14, .names = "Zelma, Zemgus, Virma" },
    Data{ .month = 8, .day = 15, .names = "Zenta, Dzelde, Zelda" },
    Data{ .month = 8, .day = 16, .names = "Astra, Astrīda" },
    Data{ .month = 8, .day = 17, .names = "Vineta, Oļegs" },
    Data{ .month = 8, .day = 18, .names = "Liene, Helēna, Elena, Ellena, Liena" },
    Data{ .month = 8, .day = 19, .names = "Melānija, Imanta" },
    Data{ .month = 8, .day = 20, .names = "Bernhards, Boriss, Rojs" },
    Data{ .month = 8, .day = 21, .names = "Janīna, Linda" },
    Data{ .month = 8, .day = 22, .names = "Rudīte, Everts" },
    Data{ .month = 8, .day = 23, .names = "Vitālijs, Ralfs, Valgudis" },
    Data{ .month = 8, .day = 24, .names = "Bērtulis, Boļeslavs" },
    Data{ .month = 8, .day = 25, .names = "Ludvigs, Ludis, Ivonna, Patrīcija, Patriks" },
    Data{ .month = 8, .day = 26, .names = "Natālija, Tālija, Broņislavs, Broņislava" },
    Data{ .month = 8, .day = 27, .names = "Žanis, Jorens, Alens" },
    Data{ .month = 8, .day = 28, .names = "Auguste, Guste" },
    Data{ .month = 8, .day = 29, .names = "Armīns, Vismants, Aiga" },
    Data{ .month = 8, .day = 30, .names = "Alvis, Jolanta, Samanta" },
    Data{ .month = 8, .day = 31, .names = "Vilma, Aigars" },
    Data{ .month = 9, .day = 1, .names = "Ilmārs, Iluta, Austrums" },
    Data{ .month = 9, .day = 2, .names = "Elīza, Lizete, Zete" },
    Data{ .month = 9, .day = 3, .names = "Berta, Bella" },
    Data{ .month = 9, .day = 4, .names = "Dzintra, Dzintara, Dzintars" },
    Data{ .month = 9, .day = 5, .names = "Klaudija, Persijs, Vaida" },
    Data{ .month = 9, .day = 6, .names = "Maigonis, Magnuss, Mariuss" },
    Data{ .month = 9, .day = 7, .names = "Regīna, Ermīns" },
    Data{ .month = 9, .day = 8, .names = "Ilga" },
    Data{ .month = 9, .day = 9, .names = "Bruno, Telma" },
    Data{ .month = 9, .day = 10, .names = "Jausma, Albertīne" },
    Data{ .month = 9, .day = 11, .names = "Signe, Signija" },
    Data{ .month = 9, .day = 12, .names = "Erna, Evita, Eva" },
    Data{ .month = 9, .day = 13, .names = "Iza, Izabella" },
    Data{ .month = 9, .day = 14, .names = "Sanita, Santa, Sanda, Sanija, Sandija" },
    Data{ .month = 9, .day = 15, .names = "Sandra, Gunvaldis, Gunvaris, Sondra" },
    Data{ .month = 9, .day = 16, .names = "Asja, Asnate, Dāgs" },
    Data{ .month = 9, .day = 17, .names = "Vera, Vaira, Vairis, Vaiva" },
    Data{ .month = 9, .day = 18, .names = "Liesma, Elita, Alita" },
    Data{ .month = 9, .day = 19, .names = "Verners, Muntis" },
    Data{ .month = 9, .day = 20, .names = "Guntra, Ginters, Marianna" },
    Data{ .month = 9, .day = 21, .names = "Modris, Matīss, Mariss" },
    Data{ .month = 9, .day = 22, .names = "Māris, Mārica, Maigurs" },
    Data{ .month = 9, .day = 23, .names = "Vanda, Veneranda, Venija" },
    Data{ .month = 9, .day = 24, .names = "Agris, Agrita" },
    Data{ .month = 9, .day = 25, .names = "Rodrigo, Rauls" },
    Data{ .month = 9, .day = 26, .names = "Gundars, Kurts, Knuts" },
    Data{ .month = 9, .day = 27, .names = "Ādolfs, Ilgonis" },
    Data{ .month = 9, .day = 28, .names = "Sergejs, Svetlana, Lana" },
    Data{ .month = 9, .day = 29, .names = "Miķelis, Mikus, Miks, Mihails, Jumis" },
    Data{ .month = 9, .day = 30, .names = "Elma, Menarda, Elna" },
    Data{ .month = 10, .day = 1, .names = "Zanda, Lāsma, Zandis" },
    Data{ .month = 10, .day = 2, .names = "Ilma, Skaidris" },
    Data{ .month = 10, .day = 3, .names = "Elza, Ilizana" },
    Data{ .month = 10, .day = 4, .names = "Modra, Francis, Dmitrijs" },
    Data{ .month = 10, .day = 5, .names = "Amālija, Amēlija" },
    Data{ .month = 10, .day = 6, .names = "Monika, Zilgma, Zilga" },
    Data{ .month = 10, .day = 7, .names = "Daumants, Druvvaldis" },
    Data{ .month = 10, .day = 8, .names = "Aina, Anete" },
    Data{ .month = 10, .day = 9, .names = "Elga, Helga, Elgars" },
    Data{ .month = 10, .day = 10, .names = "Arvīds, Arvis, Druvis" },
    Data{ .month = 10, .day = 11, .names = "Monta, Tince, Silva" },
    Data{ .month = 10, .day = 12, .names = "Valfrīds, Kira" },
    Data{ .month = 10, .day = 13, .names = "Irma, Mirga" },
    Data{ .month = 10, .day = 14, .names = "Vilhelmīne, Minna" },
    Data{ .month = 10, .day = 15, .names = "Eda, Hedviga, Helvijs" },
    Data{ .month = 10, .day = 16, .names = "Daiga, Dinija, Dinārs" },
    Data{ .month = 10, .day = 17, .names = "Gaits, Karīna, Gaitis" },
    Data{ .month = 10, .day = 18, .names = "Rolands, Rolanda, Ronalds, Erlends, Lūkass" },
    Data{ .month = 10, .day = 19, .names = "Elīna, Drosma, Drosmis" },
    Data{ .month = 10, .day = 20, .names = "Leonīds, Leonīda" },
    Data{ .month = 10, .day = 21, .names = "Urzula, Severīns" },
    Data{ .month = 10, .day = 22, .names = "Īrisa, Irīda, Airisa" },
    Data{ .month = 10, .day = 23, .names = "Daina, Dainis, Dainida" },
    Data{ .month = 10, .day = 24, .names = "Renāte, Modrīte, Mudrīte" },
    Data{ .month = 10, .day = 25, .names = "Beāte, Beatrise" },
    Data{ .month = 10, .day = 26, .names = "Amanda, Kaiva, Amanta" },
    Data{ .month = 10, .day = 27, .names = "Lilita, Irita, Ita" },
    Data{ .month = 10, .day = 28, .names = "Ņina, Ninona, Antoņina, Oksana" },
    Data{ .month = 10, .day = 29, .names = "Laimonis, Elvijs, Elva, Elvis, Laimis" },
    Data{ .month = 10, .day = 30, .names = "Nadīna, Ulla, Adīna" },
    Data{ .month = 10, .day = 31, .names = "Valts, Rinalds, Rinalda" },
    Data{ .month = 11, .day = 1, .names = "Ikars" },
    Data{ .month = 11, .day = 2, .names = "Vivita, Dzīle, Viva" },
    Data{ .month = 11, .day = 3, .names = "Ērika, Dagnija" },
    Data{ .month = 11, .day = 4, .names = "Atis, Otomārs, Oto" },
    Data{ .month = 11, .day = 5, .names = "Šarlote, Lote" },
    Data{ .month = 11, .day = 6, .names = "Linards, Leons, Leo, Leonards, Leonarda" },
    Data{ .month = 11, .day = 7, .names = "Helma, Lotārs, Pērle" },
    Data{ .month = 11, .day = 8, .names = "Aleksandra, Agra" },
    Data{ .month = 11, .day = 9, .names = "Teodors" },
    Data{ .month = 11, .day = 10, .names = "Mārtiņš, Mārcis, Markuss, Marks" },
    Data{ .month = 11, .day = 11, .names = "Ojārs, Rainers, Nellija" },
    Data{ .month = 11, .day = 12, .names = "Kaija, Kornēlija" },
    Data{ .month = 11, .day = 13, .names = "Eižens, Jevgeņijs, Jevgeņija" },
    Data{ .month = 11, .day = 14, .names = "Fricis, Vikentijs, Vincents" },
    Data{ .month = 11, .day = 15, .names = "Leopolds, Undīne, Unda" },
    Data{ .month = 11, .day = 16, .names = "Banga, Glorija" },
    Data{ .month = 11, .day = 17, .names = "Hugo, Uga, Uģis" },
    Data{ .month = 11, .day = 18, .names = "Aleksandrs, Doloresa, Brīve" },
    Data{ .month = 11, .day = 19, .names = "Elizabete, Liza, Līze, Betija" },
    Data{ .month = 11, .day = 20, .names = "Anda, Andīna, Vigo" },
    Data{ .month = 11, .day = 21, .names = "Zeltīte, Andis" },
    Data{ .month = 11, .day = 22, .names = "Aldis, Alfons, Aldris" },
    Data{ .month = 11, .day = 23, .names = "Zigrīda, Zigfrīda, Zigrīds" },
    Data{ .month = 11, .day = 24, .names = "Velta, Velda" },
    Data{ .month = 11, .day = 25, .names = "Katrīna, Kate, Kadrija, Trīne, Katrīne" },
    Data{ .month = 11, .day = 26, .names = "Konrāds, Sebastians" },
    Data{ .month = 11, .day = 27, .names = "Lauris, Norberts" },
    Data{ .month = 11, .day = 28, .names = "Rita, Vita, Olita" },
    Data{ .month = 11, .day = 29, .names = "Ignats, Virgīnija" },
    Data{ .month = 11, .day = 30, .names = "Andrievs, Andrejs, Andris" },
    Data{ .month = 12, .day = 1, .names = "Arnolds, Emanuels" },
    Data{ .month = 12, .day = 2, .names = "Meta, Sniedze" },
    Data{ .month = 12, .day = 3, .names = "Evija, Raita, Jogita, Ako" },
    Data{ .month = 12, .day = 4, .names = "Baiba, Barbara, Barba" },
    Data{ .month = 12, .day = 5, .names = "Sabīne, Sarma, Klaudijs" },
    Data{ .month = 12, .day = 6, .names = "Nikolajs, Niklāvs, Niks, Nikola" },
    Data{ .month = 12, .day = 7, .names = "Antonija, Anta, Dzirkstīte" },
    Data{ .month = 12, .day = 8, .names = "Gunārs, Vladimirs, Gunis" },
    Data{ .month = 12, .day = 9, .names = "Tabita, Sarmīte" },
    Data{ .month = 12, .day = 10, .names = "Guna, Judīte" },
    Data{ .month = 12, .day = 11, .names = "Voldemārs, Valdemārs, Valdis" },
    Data{ .month = 12, .day = 12, .names = "Otīlija, Iveta" },
    Data{ .month = 12, .day = 13, .names = "Lūcija, Veldze" },
    Data{ .month = 12, .day = 14, .names = "Auseklis, Gaisma" },
    Data{ .month = 12, .day = 15, .names = "Johanna, Hanna, Jana" },
    Data{ .month = 12, .day = 16, .names = "Alvīne" },
    Data{ .month = 12, .day = 17, .names = "Hilda, Teiksma" },
    Data{ .month = 12, .day = 18, .names = "Kristaps, Kristofers, Krists, Klinta, Kristers" },
    Data{ .month = 12, .day = 19, .names = "Lelde, Sarmis" },
    Data{ .month = 12, .day = 20, .names = "Arta, Minjona" },
    Data{ .month = 12, .day = 21, .names = "Toms, Tomass, Saulcerīte" },
    Data{ .month = 12, .day = 22, .names = "Saulvedis, Saule" },
    Data{ .month = 12, .day = 23, .names = "Viktorija, Balva" },
    Data{ .month = 12, .day = 24, .names = "Ādams, Ieva" },
    Data{ .month = 12, .day = 25, .names = "Stella, Larisa" },
    Data{ .month = 12, .day = 26, .names = "Dainuvīte, Gija, Megija" },
    Data{ .month = 12, .day = 27, .names = "Elmārs, Inita, Helmārs" },
    Data{ .month = 12, .day = 28, .names = "Inga, Ivita, Irvita, Ingeborga" },
    Data{ .month = 12, .day = 29, .names = "Solveiga, Ilgona" },
    Data{ .month = 12, .day = 30, .names = "Dāvids, Dāvis, Dāniels, Daniela, Daniels" },
    Data{ .month = 12, .day = 31, .names = "Silvestrs, Silvis, Kalvis" },
};
